/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'IFa6Solid:appleWhole': typeof import('~icons/fa6-solid/apple-whole')['default']
    'IFa6Solid:candyCane': typeof import('~icons/fa6-solid/candy-cane')['default']
    'IFa6Solid:userSecret': typeof import('~icons/fa6-solid/user-secret')['default']
    IFa6SolidAppleWhole: typeof import('~icons/fa6-solid/apple-whole')['default']
    IFaSolidUserSecret: typeof import('~icons/fa-solid/user-secret')['default']
    'ILineMd:beerAltTwotoneLoop': typeof import('~icons/line-md/beer-alt-twotone-loop')['default']
    ILocalBar3: typeof import('~icons/local/bar3')['default']
    ILocalClear: typeof import('~icons/local/clear')['default']
    ILocalCopy: typeof import('~icons/local/copy')['default']
    ILocalLogo: typeof import('~icons/local/logo')['default']
    ILocalSwap: typeof import('~icons/local/swap')['default']
    'IMaterialSymbols:10k': typeof import('~icons/material-symbols/10k')['default']
    IMdiAccount: typeof import('~icons/mdi/account')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
