/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'ILineMd:beerAltTwotoneLoop': typeof import('~icons/line-md/beer-alt-twotone-loop')['default']
    ILocalBar3: typeof import('~icons/local/bar3')['default']
    ILocalClear: typeof import('~icons/local/clear')['default']
    ILocalCopy: typeof import('~icons/local/copy')['default']
    ILocalLogo: typeof import('~icons/local/logo')['default']
    ILocalSwap: typeof import('~icons/local/swap')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
